### ISSUE TITLE
Vue.js compilation failed.

### ISSUE THREAD

**Issue by ofilangi** [p2m2/Discovery#210]
```bash
[npaulhe@clt-npaulhe23-p ~/Workspaces/mth2-wp5-vue3/metabohub-forum-library (dev)]$ npm run build-lib

> @metabohub/forum-library@0.0.1 build-lib
> npm run pres-build  && vue-tsc --noEmit && vite build


> @metabohub/forum-library@0.0.1 pres-build
> node git-version.cjs && copyfiles -f "./src/assets/*.json" ./public/assets/ && vue-tsc --noEmit

vite v3.2.5 building for production...
✓ 7945 modules transformed.
dist/components/core/MthForumFormFinder.vue.d.ts              0.40 KiB
dist/components/core/MthForumFormFinder.vue.d.ts.map          0.21 KiB
dist/components/core/MthForumLiteratureDisplay.vue.d.ts       0.42 KiB
dist/components/core/MthForumLiteratureDisplay.vue.d.ts.map   0.22 KiB
dist/components/core/MthForumResultsDisplay.vue.d.ts          0.41 KiB
dist/components/core/MthForumResultsDisplay.vue.d.ts.map      0.22 KiB
dist/src/components/main.css                                  101.59 KiB / gzip: 14.50 KiB
dist/mth-forum-lib-vue-ts.es.js                               8219.39 KiB / gzip: 1833.77 KiB
dist/components/core/MthForumFormFinder.vue.d.ts              0.40 KiB
dist/components/core/MthForumFormFinder.vue.d.ts.map          0.21 KiB
dist/components/core/MthForumLiteratureDisplay.vue.d.ts       0.42 KiB
dist/components/core/MthForumLiteratureDisplay.vue.d.ts.map   0.22 KiB
dist/components/core/MthForumResultsDisplay.vue.d.ts          0.41 KiB
dist/components/core/MthForumResultsDisplay.vue.d.ts.map      0.22 KiB
dist/src/components/main.css                                  101.59 KiB / gzip: 14.50 KiB
dist/mth-forum-lib-vue-ts.cjs.js                              6135.43 KiB / gzip: 1637.42 KiB
[vite:esbuild-transpile] Maximum call stack size exceeded

[vite:dts] Start generate declaration files...
[vite:dts] Declaration files built in 7595ms.

error during build:
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Object.renderChunk (file:///home/npaulhe/Workspaces/mth2-wp5-vue3/metabohub-forum-library/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:13495:41)
    at async Chunk.render (file:///home/npaulhe/Workspaces/mth2-wp5-vue3/metabohub-forum-library/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:14913:20)
    at async file:///home/npaulhe/Workspaces/mth2-wp5-vue3/metabohub-forum-library/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:15812:40
    at async Promise.all (index 0)
    at async Bundle.addFinalizedChunksToBundle (file:///home/npaulhe/Workspaces/mth2-wp5-vue3/metabohub-forum-library/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:15810:9)
    at async Bundle.generate (file:///home/npaulhe/Workspaces/mth2-wp5-vue3/metabohub-forum-library/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:15790:13)
    at async file:///home/npaulhe/Workspaces/mth2-wp5-vue3/metabohub-forum-library/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:23795:27
    at async catchUnfinishedHookActions (file:///home/npaulhe/Workspaces/mth2-wp5-vue3/metabohub-forum-library/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:23126:20)
    at async doBuild (file:///home/npaulhe/Workspaces/mth2-wp5-vue3/metabohub-forum-library/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45715:22)
```

et le "hack" que j'avais fait pour fixer dans le `.gitlab-ci.yaml`

```yml
build - library:
  stage: build
  tags:
    - docker
  before_script:
    - echo "==================================";
    - echo "[info] clean generated sources";
    - rm -rf $CI_PROJECT_DIR/dist
    - echo "[info] init node modules ";
    - npm install
    - echo "[info] increase ressources ";
    - export NODE_OPTIONS=--max_old_space_size=8192
  script:
    - echo "==================================";
    - echo "[info] vuejs build library ~ small hack first one fails";
    - (npm run build-lib && npm pack) || (npm run build-lib && npm pack)
```
